pipeline {

    agent any

    environment {
        PROJECT_NAME = "Kubernetes Platform Engineering"
        IMAGE_NAME = "sahilsinghchib/ecommerce-backend"
        IMAGE_TAG = "1.0.4"
    }

    stages {

        stage('Environment Variables') {
            steps {
                echo "Project: ${PROJECT_NAME}"
                sh 'echo Docker Image: $IMAGE_NAME'
                sh 'echo Docker Tag: $IMAGE_TAG'
            }
        }

        stage('Workspace Info') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }

    }

}
